import base64

import structlog

from chiron.github.api import GitHubAPI
from chiron.models import PRInfo, ReviewComment, ReviewResult
from chiron.remediation.fix_generator import generate_fix_for_file
from chiron.remediation.patch import PatchBlock, apply_patch
from chiron.remediation.validator import validate_patch

logger = structlog.get_logger("chiron.remediation.loop")


async def remediate_file(
    api: GitHubAPI,
    pr_info: PRInfo,
    file_path: str,
    comments: list[ReviewComment],
    max_attempts: int = 3,
) -> str | None:
    """Attempt to fix a single file, with retries."""
    try:
        original_content = await api.get_file_contents(
            pr_info.owner, pr_info.repo, file_path, pr_info.head_ref
        )
    except Exception as e:
        logger.error("Failed to fetch file contents", file=file_path, error=str(e))
        return None

    current_content = original_content
    for attempt in range(max_attempts):
        logger.info("Generating fix", file=file_path, attempt=attempt + 1)

        try:
            fix = await generate_fix_for_file(current_content, comments)

            blocks = [PatchBlock(search=fix.search, replace=fix.replace)]
            new_content = apply_patch(current_content, blocks)

            if validate_patch(new_content, file_path):
                logger.info("Patch generated and validated successfully", file=file_path)
                return new_content
            else:
                logger.warning("Patch failed validation", file=file_path)
                # Future: Feed validation error back to the LLM for retry

        except Exception as e:
            logger.error("Failed to generate or apply fix", file=file_path, error=str(e))

    return None


async def process_remediation(api: GitHubAPI, pr_info: PRInfo, review_result: ReviewResult) -> None:
    """Process all comments and generate fixes."""
    comments_by_file: dict[str, list[ReviewComment]] = {}
    for comment in review_result.comments:
        if comment.severity in ["critical", "warning"]:
            if comment.path not in comments_by_file:
                comments_by_file[comment.path] = []
            comments_by_file[comment.path].append(comment)

    if not comments_by_file:
        logger.info("No actionable comments for remediation", pr=pr_info.number)
        return

    file_changes = []

    for file_path, comments in comments_by_file.items():
        new_content = await remediate_file(api, pr_info, file_path, comments)
        if new_content:
            contents_base64 = base64.b64encode(new_content.encode("utf-8")).decode("utf-8")
            file_changes.append({"path": file_path, "contents_base64": contents_base64})

    if not file_changes:
        logger.info("No successful fixes generated", pr=pr_info.number)
        return

    from chiron.config import get_settings

    settings = get_settings()

    if settings.fix_strategy == "direct":
        branch = pr_info.head_ref
        message = f"Chiron: applied {len(file_changes)} autonomous fixes"
        try:
            await api.push_commit(
                pr_info.owner, pr_info.repo, branch, pr_info.head_sha, file_changes, message
            )
            logger.info("Pushed fixes directly to PR branch", pr=pr_info.number)
            from chiron.observability.health import record_fix_applied

            for _ in file_changes:
                record_fix_applied()
        except Exception as e:
            logger.error("Failed to push commit", error=str(e))

    elif settings.fix_strategy == "branch":
        import uuid

        short_hash = str(uuid.uuid4())[:8]
        new_branch = f"chiron/fix-{pr_info.number}-{short_hash}"
        message = f"Chiron: applied {len(file_changes)} autonomous fixes"

        try:
            # 1. Create the new branch from the head_sha
            await api.create_branch(pr_info.owner, pr_info.repo, new_branch, pr_info.head_sha)

            # 2. Push the commit to the new branch
            await api.push_commit(
                pr_info.owner, pr_info.repo, new_branch, pr_info.head_sha, file_changes, message
            )

            # 3. Create a pull request targeting the original PR's branch
            pr_title = f"Chiron Fixes for PR #{pr_info.number}"
            pr_body = (
                f"This PR contains autonomous fixes generated by Chiron "
                f"for issues found in #{pr_info.number}."
            )
            await api.create_pull_request(
                pr_info.owner, pr_info.repo, pr_title, new_branch, pr_info.head_ref, pr_body
            )
            logger.info(
                "Created fix PR successfully", base_pr=pr_info.number, fix_branch=new_branch
            )

            from chiron.observability.health import record_fix_applied

            for _ in file_changes:
                record_fix_applied()
        except Exception as e:
            logger.error("Failed to execute branch strategy", error=str(e))
